name: chef_wizz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  favorite_button: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.20.5
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.14
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1
  responsive_framework: ^1.5.1
  rxdart: ^0.28.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_localization: ^0.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  integration_test:
    sdk: flutter
  intl_utils: ^2.8.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.3

dependency_overrides:
  dio: 5.3.0 # https://github.com/Milad-Akarie/auto_route_library/issues/1005

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    exclude:
      - assets/env/*
    outputs:
      class_name: AppAssets

flutter:
  uses-material-design: true
  generate: true
  
  assets:
   - assets/images/
   - .env
   - recipes.json

  fonts:
  - family: Satoshi
    fonts:
      - asset: assets/fonts/Satoshi/Satoshi-Light.otf
        weight: 400
      - asset: assets/fonts/Satoshi/Satoshi-LightItalic.otf
        weight: 400
        style: italic
      - asset: assets/fonts/Satoshi/Satoshi-Regular.otf
        weight: 500
      - asset: assets/fonts/Satoshi/Satoshi-Italic.otf
        weight: 500
        style: italic
      - asset: assets/fonts/Satoshi/Satoshi-Medium.otf
        weight: 600
      - asset: assets/fonts/Satoshi/Satoshi-MediumItalic.otf
        weight: 600
        style: italic
      - asset: assets/fonts/Satoshi/Satoshi-Bold.otf
        weight: 700
      - asset: assets/fonts/Satoshi/Satoshi-BoldItalic.otf
        weight: 700
        style: italic
      - asset: assets/fonts/Satoshi/Satoshi-Black.otf
        weight: 800
      - asset: assets/fonts/Satoshi/Satoshi-BlackItalic.otf
        weight: 800
        style: italic
 
