import Navbar from "../../component/Navbar";
import data from "../../../data.json";
import MetricCard from "../../component/MetricCard";
import { useEffect, useState } from "react";
import ActivityChart from "./ActivityChart";
import UserTable from "./UserTable";
import { useNavigate } from "react-router-dom";

interface MetricsData {
  totalUsers: number;
  activeSessions: number;
  revenue: string;
}

interface HomeProps {
  setIsAuthenticated: (isAuthenticated: boolean) => void;
  isAuthenticated: boolean;
}

const Home = ({ setIsAuthenticated, isAuthenticated }: HomeProps) => {
  const navigate = useNavigate();
  const [metricsData, setMetricsData] = useState<MetricsData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setMetricsData(data.metrics);
      setLoading(false);
    }, 2000);
  }, []);

  if (!isAuthenticated) {
    navigate("/login");
    return null;
  }

  return (
    <div className="min-h-screen bg-background" id="dashboard">
      <Navbar setIsAuthenticated={setIsAuthenticated} />

      {/* Metrics section */}
      <div className="container mx-auto py-8" id="metrics">
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 p-4 ">
          {loading ? (
            <>
              <MetricCard loading />
              <MetricCard loading />
              <MetricCard loading />
            </>
          ) : (
            <>
              <MetricCard
                title="Total Users"
                value={metricsData?.totalUsers}
                description="The total number of users registered on the platform."
              />
              <MetricCard
                title="Active Sessions"
                value={metricsData?.activeSessions}
                description="The number of active sessions currently on the platform."
              />
              <MetricCard
                title="Revenue"
                value={metricsData?.revenue}
                description="The total revenue generated by the platform."
              />
            </>
          )}
        </div>
      </div>

      {/* Activity Chart section */}
      <div className="container mx-auto py-8 px-4" id="activity">
        <ActivityChart />
      </div>

      {/* User Table section */}
      <div className="container mx-auto py-8 px-4" id="userList">
        <UserTable />
      </div>
    </div>
  );
};

export default Home;
