export const userActionTypes = {
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  LOADUSER_SUCCESS: 'LOADUSER_SUCCESS',
  LOADUSER_FAIL: 'LOADUSER_FAIL',
};
